branch-defaults:
  default:
    environment: lcog-internal-env
    group_suffix: null
  master:
    environment: lcog-internal-env
global:
  application_name: lcog-internal
  branch: null
  default_ec2_keyname: dan-lcog
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
